---
sidebar: sidebar 
permalink: concept_api_understanding_scripts.html 
keywords: rest api, deploy rest api, rest, python, python scripts, understanding 
summary: Mit den Python-Beispielskripten können Sie mehrere verschiedene Aufgaben ausführen. Sie sollten die Skripte verstehen, bevor Sie sie in einer Live-Deploy-Instanz verwenden. 
---
= Verstehen Sie die Python-Skripte
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mit den Python-Beispielskripten können Sie mehrere verschiedene Aufgaben ausführen. Sie sollten die Skripte verstehen, bevor Sie sie in einer Live-Deploy-Instanz verwenden.



== Gemeinsame Designeigenschaften

Die Skripte wurden mit folgenden gemeinsamen Merkmalen entworfen:

* Ausführung über die Befehlszeilenschnittstelle auf einem Client-Rechner
Sie können die Python-Skripte von jedem ordnungsgemäß konfigurierten Client-Computer aus ausführen. Weitere Informationen finden Sie unter _before you begin_.
* Akzeptieren Sie CLI-Eingabeparameter
Jedes Skript wird über die CLI über Eingabeparameter gesteuert.
* Eingabedatei lesen
Jedes Skript liest eine Eingabedatei basierend auf ihrem Zweck. Wenn Sie ein Cluster erstellen oder löschen, müssen Sie eine JSON-Konfigurationsdatei angeben. Beim Hinzufügen einer Node-Lizenz müssen Sie eine gültige Lizenzdatei angeben.
* Verwenden Sie ein gemeinsames Supportmodul
Das gemeinsame Supportmodul _Deploy_Requests.py_ enthält eine einzelne Klasse. Sie wird von jedem der Skripte importiert und verwendet.




== Erstellen eines Clusters

Sie können mithilfe des Skripts Cluster.py einen ONTAP Select Cluster erstellen. Auf der Grundlage der CLI-Parameter und der Inhalte der JSON-Eingabedatei können Sie das Skript in Ihre Bereitstellungsumgebung wie folgt ändern:

[NOTE]
====
* Ab ONTAP Select 9.10.1 können Sie kein neues Cluster mehr auf dem KVM-Hypervisor implementieren.
* Ab ONTAP Select 9.11.1 sind alle Managementfunktionen nicht mehr für vorhandene KVM-Cluster und -Hosts verfügbar, mit Ausnahme der Funktionen zum Offline- und Löschen.


====
* Hypervisor
Sie können ESXI oder KVM bereitstellen (je nach Bereitstellungsversion). Bei der Implementierung in ESXi wird der Hypervisor durch vCenter gemanagt oder es kann ein Standalone-Host sein.
* Clustergröße
Sie können ein Single-Node- oder Multi-Node-Cluster implementieren.
* Evaluierungs- oder Produktionslizenz
Sie können einen Cluster mit einer Evaluierungs- oder erworbenen Lizenz für die Produktion bereitstellen.


Die CLI-Eingabeparameter für das Skript umfassen:

* Hostname oder IP-Adresse des Deploy-Servers
* Passwort für das Admin-Benutzerkonto
* Name der JSON-Konfigurationsdatei
* Ausführliche Flag für Nachrichtenausgabe




== Fügen Sie eine Node-Lizenz hinzu

Wenn Sie sich für die Bereitstellung eines Produktionsclusters entscheiden, müssen Sie für jeden Knoten eine Lizenz hinzufügen, indem Sie das Skript _add_license.py_ verwenden. Sie können die Lizenz vor oder nach dem Implementieren des Clusters hinzufügen.

Die CLI-Eingabeparameter für das Skript umfassen:

* Hostname oder IP-Adresse des Deploy-Servers
* Passwort für das Admin-Benutzerkonto
* Name der Lizenzdatei
* ONTAP-Benutzername mit Berechtigungen zum Hinzufügen der Lizenz
* Kennwort für den ONTAP-Benutzer




== Löschen eines Clusters

Sie können einen vorhandenen ONTAP Select-Cluster mithilfe des Skripts _delete_Cluster.py_ löschen.

Die CLI-Eingabeparameter für das Skript umfassen:

* Hostname oder IP-Adresse des Deploy-Servers
* Passwort für das Admin-Benutzerkonto
* Name der JSON-Konfigurationsdatei

